[2025-01-24T00:00:07.817+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: data_ingestion.start_ingestion scheduled__2025-01-23T00:00:00+00:00 [queued]>
[2025-01-24T00:00:07.825+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: data_ingestion.start_ingestion scheduled__2025-01-23T00:00:00+00:00 [queued]>
[2025-01-24T00:00:07.826+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-01-24T00:00:07.826+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-01-24T00:00:07.826+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-01-24T00:00:07.923+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): start_ingestion> on 2025-01-23 00:00:00+00:00
[2025-01-24T00:00:07.931+0000] {standard_task_runner.py:55} INFO - Started process 36307 to run task
[2025-01-24T00:00:07.935+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion', 'start_ingestion', 'scheduled__2025-01-23T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/ingestion/dags/news.py', '--cfg-path', '/tmp/tmpadnxtw3n']
[2025-01-24T00:00:07.937+0000] {standard_task_runner.py:83} INFO - Job 10: Subtask start_ingestion
[2025-01-24T00:00:07.984+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:249 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-24T00:00:07.999+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.10/site-packages/***/utils/sqlalchemy.py:121 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-24T00:00:08.020+0000] {task_command.py:389} INFO - Running <TaskInstance: data_ingestion.start_ingestion scheduled__2025-01-23T00:00:00+00:00 [running]> on host 01ffd301dd0f
[2025-01-24T00:00:08.180+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion
AIRFLOW_CTX_TASK_ID=start_ingestion
AIRFLOW_CTX_EXECUTION_DATE=2025-01-23T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-01-23T00:00:00+00:00
[2025-01-24T00:01:19.803+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.10/site-packages/spacy/util.py:910 UserWarning: [W095] Model 'en_pipeline' (0.0.0) was trained with spaCy v3.2.0 and may not be 100% compatible with the current version (3.7.6). If you see errors or degraded performance, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
[2025-01-24T00:02:06.701+0000] {logging_mixin.py:137} WARNING - 2025-01-24 00:02:06,701 - INFO - main.py -   Text processed 100 documents
[2025-01-24T00:02:06.701+0000] {main.py:34} INFO - Text processed 100 documents
[2025-01-24T00:02:06.714+0000] {logging_mixin.py:137} WARNING - 2025-01-24 00:02:06,714 - INFO - main.py -   Split sentence 100 documents
[2025-01-24T00:02:06.714+0000] {main.py:41} INFO - Split sentence 100 documents
[2025-01-24T00:02:06.884+0000] {milvus_client.py:658} DEBUG - Created new connection using: 164e08fee9b943289763cc91ff3ca3af
[2025-01-24T00:02:06.888+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py:2554 UserWarning: MongoClient opened before fork. May not be entirely fork-safe, proceed with caution. See PyMongo's documentation for details: https://www.mongodb.com/docs/languages/python/pymongo-driver/current/faq/#is-pymongo-fork-safe-
[2025-01-24T00:02:08.823+0000] {logging_mixin.py:137} WARNING - Processing batches: 0it [00:00, ?it/s]
[2025-01-24T00:02:37.097+0000] {logging_mixin.py:137} WARNING - Processing batches: 1it [00:28, 28.27s/it]
[2025-01-24T00:04:15.299+0000] {logging_mixin.py:137} WARNING - Processing batches: 2it [02:06, 69.41s/it]
[2025-01-24T00:05:57.092+0000] {logging_mixin.py:137} WARNING - Processing batches: 3it [03:48, 84.20s/it]
[2025-01-24T00:07:09.699+0000] {logging_mixin.py:137} WARNING - Processing batches: 4it [05:00, 79.62s/it]
[2025-01-24T00:09:20.092+0000] {logging_mixin.py:137} WARNING - Processing batches: 5it [07:11, 97.93s/it]
[2025-01-24T00:11:38.499+0000] {logging_mixin.py:137} WARNING - Processing batches: 6it [09:29, 111.69s/it]
[2025-01-24T00:14:09.501+0000] {logging_mixin.py:137} WARNING - Processing batches: 7it [12:00, 124.54s/it]
[2025-01-24T00:16:22.299+0000] {logging_mixin.py:137} WARNING - Processing batches: 8it [14:13, 127.17s/it]
[2025-01-24T00:19:43.905+0000] {logging_mixin.py:137} WARNING - Processing batches: 9it [17:35, 150.44s/it]
[2025-01-24T00:20:17.108+0000] {logging_mixin.py:137} WARNING - Processing batches: 10it [18:08, 114.25s/it]
[2025-01-24T00:21:40.908+0000] {logging_mixin.py:137} WARNING - Processing batches: 11it [19:32, 104.93s/it]
[2025-01-24T00:23:50.520+0000] {logging_mixin.py:137} WARNING - Processing batches: 12it [21:41, 112.44s/it]
[2025-01-24T00:25:01.310+0000] {logging_mixin.py:137} WARNING - Processing batches: 13it [22:52, 99.82s/it] 
[2025-01-24T00:27:13.324+0000] {logging_mixin.py:137} WARNING - Processing batches: 14it [25:04, 109.54s/it]
[2025-01-24T00:28:42.114+0000] {logging_mixin.py:137} WARNING - Processing batches: 15it [26:33, 103.29s/it]
[2025-01-24T00:29:53.128+0000] {logging_mixin.py:137} WARNING - Processing batches: 16it [27:44, 93.57s/it] 
[2025-01-24T00:30:31.118+0000] {logging_mixin.py:137} WARNING - Processing batches: 17it [28:22, 76.86s/it]
[2025-01-24T00:30:59.529+0000] {logging_mixin.py:137} WARNING - Processing batches: 18it [28:50, 62.30s/it]
[2025-01-24T00:31:55.118+0000] {logging_mixin.py:137} WARNING - Processing batches: 19it [29:46, 60.29s/it]
[2025-01-24T00:34:13.522+0000] {logging_mixin.py:137} WARNING - Processing batches: 20it [32:04, 83.74s/it]
[2025-01-24T00:34:13.523+0000] {logging_mixin.py:137} WARNING - Processing batches: 20it [32:04, 96.23s/it]
[2025-01-24T00:34:13.584+0000] {logging_mixin.py:137} WARNING - 2025-01-24 00:34:13,584 - ERROR - main.py -   Failed to write: object of type 'Article' has no len()
[2025-01-24T00:34:13.584+0000] {main.py:57} ERROR - Failed to write: object of type 'Article' has no len()
[2025-01-24T00:34:13.585+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingestion/main.py", line 55, in manage_data_processing
    batch_upsert(collection, data)
  File "/opt/airflow/dags/ingestion/db/write.py", line 69, in batch_upsert
    if not isinstance(data, list):
TypeError: object of type 'Article' has no len()
[2025-01-24T00:34:13.593+0000] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion, task_id=start_ingestion, execution_date=20250123T000000, start_date=20250124T000007, end_date=20250124T003413
[2025-01-24T00:34:13.664+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 10 for task start_ingestion (object of type 'Article' has no len(); 36307)
[2025-01-24T00:34:13.739+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-01-24T00:34:13.752+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
